/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author agus
 */
public class SPMT extends javax.swing.JApplet { 
    private GestorFiltros g = new GestorFiltros();
    private boolean activado = false;
    private boolean mantener = false;
    private boolean reiniciar = false;
    private double velocidad_almacenada = 0;
    /**
     * Initializes the applet SPMT
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SPMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SPMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SPMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SPMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        this.setSize(400, 300);
        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    
      
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radial2Lcd1 = new eu.hansolo.steelseries.gauges.Radial2Lcd();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        displaySingle1 = new eu.hansolo.steelseries.gauges.DisplaySingle();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(232, 27, 27));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("APAGADO");

        jToggleButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(29, 221, 72));
        jToggleButton1.setText("ENCENDER");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jToggleButton2.setText("ACELERAR");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jToggleButton3.setText("FRENAR");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Velocidad Almacenada");

        jToggleButton5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jToggleButton5.setText("MANTENER");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jToggleButton6.setText("REINICAR");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(radial2Lcd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jToggleButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jToggleButton2)
                                            .addComponent(jToggleButton5))
                                        .addGap(92, 92, 92)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jToggleButton6)
                                            .addComponent(jToggleButton3)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(displaySingle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radial2Lcd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(displaySingle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton2)
                            .addComponent(jToggleButton3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton5)
                            .addComponent(jToggleButton6))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if(jToggleButton1.isSelected()){
            if(g.getState() == Thread.State.RUNNABLE) {
                ((Thread)g).start();
            }
            radial2Lcd1.setValueAnimated(g.s.getVelocidadLineal());
            /*jLabel12.setText(Double.toString(g.s.getVelocidadLineal()));
            jLabel8.setText(Double.toString(g.s.getContador_reciente()));
            jLabel10.setText(Double.toString(g.s.getContador_total()));
            jLabel14.setText(Double.toString(g.s.getRpm()));*/

            jLabel2.setText("ENCENDIDO");
            jLabel2.setForeground(Color.green);

            jToggleButton1.setText("APAGAR");
            jToggleButton1.setForeground(Color.red);

            jToggleButton2.setEnabled(true);
            jToggleButton3.setEnabled(true);
            jToggleButton5.setEnabled(false);
            jToggleButton6.setEnabled(false);
            
            
            

        }
        else{
            jLabel2.setText("APAGADO");
            jLabel2.setForeground(Color.red);

            jToggleButton1.setText("ENCENDER");
            jToggleButton1.setForeground(Color.green);

            jToggleButton2.setEnabled(false);
            jToggleButton3.setEnabled(false);
            jToggleButton5.setEnabled(false);
            jToggleButton6.setEnabled(false);
            g.peticionFiltros(EstadoMotor.APAGADO);

            radial2Lcd1.setValueAnimated(g.s.getVelocidadLineal());
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        new Thread(){

            public void run(){

                while(jToggleButton2.isSelected()){
                    jToggleButton1.setEnabled(false);
                    jToggleButton3.setEnabled(false);
                    jToggleButton5.setEnabled(true);
                    jToggleButton2.setText("ACELERANDO");
                    if(!mantener)
                        g.peticionFiltros(EstadoMotor.ACELERANDO);
                    
                    
                    radial2Lcd1.setValueAnimated(g.s.getVelocidadLineal());

                    try {
                        Thread.sleep(800);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(SPMT.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }.start();
    new Thread(){
        public void run(){
            while(!jToggleButton2.isSelected() && !jToggleButton3.isSelected() && !reiniciar){
                jToggleButton5.setEnabled(false);
                if(!mantener)
                    g.peticionFiltros(EstadoMotor.ENCENDIDO);
                radial2Lcd1.setValueAnimated(g.s.getVelocidadLineal()); 
                try {
                    Thread.sleep(800);
                } catch (InterruptedException ex) {
                    Logger.getLogger(SPMT.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }
    }.start();
    if (!jToggleButton2.isSelected()){
        jToggleButton1.setEnabled(true);
        jToggleButton3.setEnabled(true);
        jToggleButton2.setText("ACELERAR");
    }

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        new Thread(){

            public void run(){
                while(jToggleButton3.isSelected()){
                    jToggleButton1.setEnabled(false);
                    jToggleButton5.setEnabled(false);
                    jToggleButton3.setText("FRENANDO");
                    g.peticionFiltros(EstadoMotor.FRENANDO);
                    jToggleButton2.setEnabled(false);
                    radial2Lcd1.setValueAnimated(g.s.getVelocidadLineal());
                    
                    try {
                        Thread.sleep(800);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(SPMT.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }.start();
        if (!jToggleButton3.isSelected()){
            jToggleButton1.setEnabled(true);
            jToggleButton3.setText("FRENAR");
            jToggleButton2.setEnabled(true);
        }
        new Thread(){
        public void run(){
            while(!jToggleButton2.isSelected() && !jToggleButton3.isSelected() && !reiniciar){
                jToggleButton5.setEnabled(false);
                g.peticionFiltros(EstadoMotor.ENCENDIDO);
                radial2Lcd1.setValueAnimated(g.s.getVelocidadLineal());
                try {
                    Thread.sleep(800);
                } catch (InterruptedException ex) {
                    Logger.getLogger(SPMT.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        }.start();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        if(!mantener){
            mantener = true;
            velocidad_almacenada = g.s.getVelocidadLineal();
            displaySingle1.setValue(velocidad_almacenada);
            jToggleButton6.setEnabled(true);
        }
        else{
            mantener = false;
            jToggleButton2.doClick();
        }
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        reiniciar = true;
        new Thread(){

            public void run(){

                while(jToggleButton6.isSelected()){
                    jToggleButton5.setEnabled(true);
                    jToggleButton6.setText("REINICIANDO");
                    if(g.s.getVelocidadLineal() < velocidad_almacenada)
                        g.peticionFiltros(EstadoMotor.ACELERANDO);
                    else if(g.s.getVelocidadLineal() > velocidad_almacenada)
                        g.peticionFiltros(EstadoMotor.FRENANDO);
                    else{
                        jToggleButton5.doClick();
                        jToggleButton6.doClick();
                    }
                                
                    radial2Lcd1.setValueAnimated(g.s.getVelocidadLineal());

                    try {
                        Thread.sleep(800);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(SPMT.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }.start();
    }//GEN-LAST:event_jToggleButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eu.hansolo.steelseries.gauges.DisplaySingle displaySingle1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private eu.hansolo.steelseries.gauges.Radial2Lcd radial2Lcd1;
    // End of variables declaration//GEN-END:variables
}
